name: Docs

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10' # Specify the Python version compatible with your project
      
      - name: Upgrade pip, wheel, and setuptools
        run: |
          python -m pip install --upgrade pip wheel setuptools
      
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        run: |
          pip install -v sphinx cython sphinx_rtd_theme
          pip install -v azure-cognitiveservices-speech numba numpy openai protobuf requests spacy tiktoken uuid6
          # Ensure you have the correct URLs for the models, if they're needed
          pip install -v en_core_web_lg@https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.7.1/en_core_web_lg-3.7.1.tar.gz
          pip install -v en_core_web_md@https://github.com/explosion/spacy-models/releases/download/en_core_web_md-3.7.1/en_core_web_md-3.7.1.tar.gz
          pip install -v en_core_web_sm@https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.7.1/en_core_web_sm-3.7.1.tar.gz
      
      - name: Sphinx build
        run: |
          sphinx-build docs _build
        env:
          OPENAI_API_KEY: dummy
          AZURE_SPEECH_KEY: dummy
          AZURE_SPEECH_REGION: dummy
      
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./_build
          force_orphan: true
