name: Build and Deploy Documentation

on:
  push:
    branches:
      - main  # or the name of your default branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3

    - name: Install Dependencies
      run: |
        pip install sphinx sphinx_rtd_theme

    - name: Generate Documentation
      run: |
        cd docs  # assuming this is where your Sphinx config is
        make html  # assuming you have a Makefile set up for Sphinx

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html  # adjust this to match your Sphinx config
